version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: "cargo"
    directory: "/native/zenohex_nif"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
